spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mockjava-trucln2
    username: kienpt
    password: abc123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: debug