spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      hibernate:
        SQL: debug