spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/user_dev?allowPublicKeyRetrieval=true&useSSL=false
    username: springmvc
    password: springmvc
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
server:
  port: 8080
